### ISSUE TITLE
Uncaught TypeError: "cwd" must be a string

### ISSUE THREAD

**Issue by pak-man** [kn1kn1/language-context-free#3]
[Enter steps to reproduce:]

1. ...install and configure atom package "language-context-free"
2. ...load a cfdg script and attempt to render it

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Debian GNU/Linux
**Thrown From**: [language-context-free](https://github.com/kn1kn1/language-context-free) package 0.8.7

### Stack Trace

Uncaught TypeError: "cwd" must be a string

```
At /usr/share/atom/resources/app/static/<embedded>:14

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:415:11)
    at Object.exports.spawn (child_process.js:508:38)
    at BufferedProcess.spawn (/usr/share/atom/resources/app/static/<embedded>:14:1035310)
    at BufferedProcess.start (/usr/share/atom/resources/app/static/<embedded>:14:1033485)
    at new BufferedProcess (/usr/share/atom/resources/app/static/<embedded>:14:1033281)
    at Object.execCfdg (/packages/language-context-free/lib/context-free-render.coffee:209:7)
    at Object.render (/packages/language-context-free/lib/context-free-render.coffee:140:6)
    at /packages/language-context-free/lib/context-free-render.coffee:80:34)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:347327)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226769)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1222903)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:282763)
```

### Commands

```
     -0:09.2.0 intentions:highlight (input.hidden-input)
     -0:08.9.0 context-free:render (input.hidden-input)
```

### Non-Core Packages

```
atom-commander 0.12.0 
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.26 
intentions 1.1.5 
language-context-free 0.8.7 
language-ini 1.20.0 
language-kivy 0.2.0 
language-openscad 0.4.3 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.2.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
remote-edit 1.9.0 
remote-ftp 2.2.0 
screen-send 1.11.0 
sftp-upload-on-change 0.1.0 
tool-bar 1.1.11 
```

**Comment by kn1kn1** [comment]
Must be fixed at https://github.com/kn1kn1/language-context-free/commit/64256c0be5c4ec7dd5b0f5330e78db65acf42428.
Try updating to v0.9.0.
Thanks for reporting.
